# Generated by Django 4.1.1 on 2023-03-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
