# Generated by Django 4.1.1 on 2023-03-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactdetails_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactDetails',
            new_name='contact',
        ),
    ]
